### ISSUE TITLE
Package unusable due to access control

### ISSUE THREAD

**Issue by avi-screenovate** [quassummanus/SwiftUI-Tooltip#2]
**Describe the bug**
I added this package to my Xcode project, and I am unable to use it because the View extension methods are not public.

**To Reproduce**
1. Add package to Xcode project
2. Import SwiftUITooltip into ContentView.swift
3. Attempt to invoke tooltip(...) method.
4. See compiler error.

**Expected behavior**
The methods should be accessible.

**Comment by LilaQ** [comment]
Will this be fixed?

**Comment by bring-shrubbery** [comment]
Hey, I didn't have any time at all for this, but I'll try to fix it todat ;)

**Comment by bring-shrubbery** [comment]
Hey @LilaQ @avi-screenovate ! It should work now :) At least it works for me :D Sorry for fixing this forever 😳

**Comment by tobyloki** [comment]
@bring-shrubbery
1. I've just started using this package (v1.0.2), and I still see this error. Would you be able to fix it?
2. Also is there an option to hide/show the tooltip? If not, would you be able to add that feature?

`'DefaultTooltipConfig' initializer is inaccessible due to 'internal' protection level`

![image](https://user-images.githubusercontent.com/35203563/125135484-e6c45780-e0bd-11eb-8955-26819789dc4a.png)

**Comment by bring-shrubbery** [comment]
@tobyloki Could you provide versions of xcode/macos you use?

**Comment by tobyloki** [comment]
I use XCode 12.5.1 and the Mac Mini 2020 with the M1 chip.

**Comment by bring-shrubbery** [comment]
Ah, my bad, somehow I missed making the initializer itself public.

**Comment by bring-shrubbery** [comment]
Try again with v1.0.3, should be working now :)

**Comment by bring-shrubbery** [comment]
@tobyloki Tell me if there are still any issues ;)

**Comment by tobyloki** [comment]
I tried it out and it works now. Thanks. I did just have to fix one build error in TooltipConfig.swift by simply removing all the keyword public as shown in the below image, and then it built successfully.

![image](https://user-images.githubusercontent.com/35203563/125525875-58de7dd5-1910-4627-a325-412ecdbe51ca.png)

**Comment by bring-shrubbery** [comment]
Weird that I didn't get this error, but I'll remove those in a bit. Thanks for helping me out solving this issue!
